AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  noteApp:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::365939108559:role/service-role/noteApp'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /items
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: '/items/{email}'
            Method: ANY
